INPUT_FILESNAME:
  CHARGES_USE: "data/Charges_use.csv"
  DAMAGES_USE: "data/Damages_use.csv"
  ENDORSE_USE: "data/Endorse_use.csv" 
  PRIMARY_PERSON_USE: "data/Primary_Person_use.csv"
  RESTRICT_USE: "data/Restrict_use.csv"
  UNITS_USE: "data/Units_use.csv"

OUTPUT_PATH:
 CASE_STUDY_JOB: "output/case_study_job.csv"


FILE_FORMATS:
  INPUT: "csv"
  OUTPUT: "csv"